---
- name: apply common configuration to all nodes
  hosts: all
  remote_user: paulius
  become: yes
  gather_facts: no

  roles:
  - common
  - pgsql
  - nginx
  - php
  - postfixadmin

- name: pgsql create user/db
  hosts: all
  remote_user: paulius
  become: yes
  become_user: postgres
  gather_facts: no

  roles:
  - pgsql_config
