---
- name: apply common configuration to all nodes
  hosts: all
  remote_user: paulius
  sudo: yes
  gather_facts: no

  roles:
  - common
  - pgsql
  - nginx
  - php

- name: pgsql create user/db
  hosts: all
  remote_user: paulius
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  roles:
  - pgsql_config
