---
- name: apply common configuration to all nodes
  hosts: all
  remote_user: paulius
  become: yes
  gather_facts: no

  roles:
  - common
  - pgsql
  - nginx
  - php
  - postfixadmin

- name: pgsql create user/db
  hosts: all
  remote_user: paulius
  become: yes
  become_user: "{{ pg_sys_user }}"
  gather_facts: no

  roles:
  - { role: pgsql_config, pg_db: "{{ pf_db }}", pg_user: "{{ pf_pg_user }}", pg_pwd:  "{{ pf_pg_pwd }}" }
