---
- name: Install PostgreSQL server
  yum: name={{ item }} state=present enablerepo={{ pg_repo }}
  with_items:
    - postgresql{{ pg_v }}-server
    - python-psycopg2

- name: check if db exists
  shell: test "0" = $( ls {{ pg_data_dir }} | wc -l )
  register: result
  failed_when: "result.rc == 2"

- name: initialize db
  command: /usr/pgsql-{{ pg_ver }}/bin/postgresql{{ pg_v }}-setup initdb
  when: "result.rc == 0"

- name: pg_hba config
  template: src=pg_hba.j2 dest=/var/lib/pgsql/{{ pg_ver }}/data/pg_hba.conf mode=0640 owner=postgres group=postgres
  notify: restart postgresql service 

- name: postgresql config
  template: src=postgresql.j2 dest=/var/lib/pgsql/{{ pg_ver }}/data/postgresql.conf mode=0640 owner={{ pg_sys_user }} group={{ pg_sys_group }}
  notify: restart postgresql service 

- name: Start postgresql service
  service: name={{ pg_service }} state=started enabled=yes
