---

- name: Install postgresql
  yum: name=postgresql94-server state=present enablerepo={{ pg_repo }}

- name: Install psycopg2
  yum: name=python-psycopg2 state=present enablerepo={{ pg_repo }}

- name: check if db exists
  command: test -d {{ pg_data_dir }}
  register: result
  ignore_errors: True

- name: initialize db
  command: /usr/pgsql-9.4/bin/postgresql94-setup initdb
  when: "result.rc != 0"

- name: pg_hba config
  template: src=pg_hba.j2 dest=/var/lib/pgsql/9.4/data/pg_hba.conf mode=0640 owner=postgres group=postgres
  notify: restart postgresql service 

- name: postgresql config
  template: src=postgresql.j2 dest=/var/lib/pgsql/9.4/data/postgresql.conf mode=0640 owner=postgres group=postgres
  notify: restart postgresql service 

- name: Start postgresql service
  service: name={{ pg_service }} state=started enabled=yes
