---

- name: install php-fpm and friends
  yum: name={{ item }}
  with_items:
    - php-common
    - php-fpm
    - php-pdo
    - php-pgsql

- name: php-fpm config
  template: src=php-fpm.conf.j2 dest=/etc/php-fpm.conf mode=0640 owner=root group=root
  notify: restart php-fpm service

- name: Create configurations for sites
  template: src=site.conf.j2 dest={{phpfpm_conf_dir}}/{{ item }}.conf
  with_items: phpfpm_sites.keys() | difference(phpfpm_remove_sites)
  notify: restart php-fpm service

- name: enable/start php-fpm
  service: name={{ php_service }} state=started enabled=yes
